# Generated by Django 4.2.1 on 2023-05-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutprogram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutProgram',
        ),
    ]
