# Generated by Django 4.2.1 on 2023-05-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutprogram',
            name='career_prospects',
        ),
        migrations.RemoveField(
            model_name='aboutprogram',
            name='funded_quota',
        ),
        migrations.RemoveField(
            model_name='aboutprogram',
            name='licensed_quota',
        ),
        migrations.RemoveField(
            model_name='aboutprogram',
            name='study_form',
        ),
        migrations.RemoveField(
            model_name='aboutprogram',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='aboutprogram',
            name='tuition_fee',
        ),
        migrations.AddField(
            model_name='aboutprogram',
            name='fields',
            field=models.ManyToManyField(to='main.field'),
        ),
    ]
