# Generated by Django 4.2.1 on 2023-05-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutprogram_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='additional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='main_img',
            field=models.ImageField(upload_to='main_images/'),
        ),
    ]
