# Generated by Django 4.2.1 on 2023-05-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_teacher_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='additional',
            field=models.CharField(default='', max_length=100),
        ),
    ]
