# Generated by Django 4.2.1 on 2024-03-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_aboutprogram_options_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва курсу')),
                ('semester', models.IntegerField(choices=[(1, 'Семестр 1'), (2, 'Семестр 2'), (3, 'Семестр 3'), (4, 'Семестр 4'), (5, 'Семестр 5'), (6, 'Семестр 6'), (7, 'Семестр 7'), (8, 'Семестр 8')], verbose_name='Семестр')),
                ('block', models.CharField(choices=[('Гуманітарний блок', 'Гуманітарний блок'), ('Природничо-науковий блок', 'Природничо-науковий блок'), ('Фаховий блок', 'Фаховий блок'), ('Фахові дисципліни вільного вибору', 'Фахові дисципліни вільного вибору')], max_length=100, verbose_name='Предметний блок')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
