# Generated by Django 4.2.1 on 2024-04-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_course_credits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
    ]
