# Generated by Django 4.2.1 on 2024-04-26 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='page_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
