# Generated by Django 4.2.1 on 2024-04-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_courseoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoption',
            options={'verbose_name': 'Додаткова опція', 'verbose_name_plural': 'Додаткові опції'},
        ),
    ]
