# Generated by Django 4.2.1 on 2024-05-12 21:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_news_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
