# Generated by Django 4.2.1 on 2024-05-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_news_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['surname'], 'verbose_name': 'Викладач', 'verbose_name_plural': 'Викладачі'},
        ),
        migrations.RemoveField(
            model_name='aboutprogram',
            name='course_map',
        ),
    ]
