# Generated by Django 4.2.1 on 2024-05-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_course_options_remove_aboutprogram_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Загальна інформація',
                'verbose_name_plural': 'Загальна інформація',
            },
        ),
        migrations.RemoveField(
            model_name='aboutprogram',
            name='fields',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='about_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_info', to='main.aboutprogram'),
        ),
    ]
